/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.omalperera.creditcardsimulator;

import java.awt.Color;
import com.omalperera.bank.TheBank_DatabaseConnector;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;



/**
 *
 * @author Omal Perera
 */
public class sampleSimulator extends javax.swing.JFrame {

    /**
     * Creates new form sampleSimulator
     */
    public sampleSimulator() {
        initComponents();
        SetIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardNum_set1 = new javax.swing.JTextField();
        cardNum_set2 = new javax.swing.JTextField();
        cardNum_set3 = new javax.swing.JTextField();
        cardNum_set4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnTransaction = new javax.swing.JButton();
        feedback = new javax.swing.JLabel();
        cashireID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Credit / Debit Card Simulator");
        setBackground(Color.WHITE);
        setMinimumSize(new java.awt.Dimension(750, 600));
        getContentPane().setLayout(null);

        cardNum_set1.setBackground(new Color(0,0,0,0));
        cardNum_set1.setFont(new java.awt.Font("OCR A Std", 0, 32)); // NOI18N
        cardNum_set1.setForeground(new java.awt.Color(247, 247, 247));
        cardNum_set1.setBorder(null);
        cardNum_set1.setOpaque(false);
        getContentPane().add(cardNum_set1);
        cardNum_set1.setBounds(130, 340, 100, 40);

        cardNum_set2.setBackground(new Color(0,0,0,0));
        cardNum_set2.setFont(new java.awt.Font("OCR A Std", 0, 32)); // NOI18N
        cardNum_set2.setForeground(new java.awt.Color(247, 247, 247));
        cardNum_set2.setBorder(null);
        cardNum_set2.setOpaque(false);
        cardNum_set2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNum_set2ActionPerformed(evt);
            }
        });
        getContentPane().add(cardNum_set2);
        cardNum_set2.setBounds(260, 340, 100, 40);

        cardNum_set3.setBackground(new Color(0,0,0,0));
        cardNum_set3.setFont(new java.awt.Font("OCR A Std", 0, 32)); // NOI18N
        cardNum_set3.setForeground(new java.awt.Color(247, 247, 247));
        cardNum_set3.setBorder(null);
        cardNum_set3.setOpaque(false);
        getContentPane().add(cardNum_set3);
        cardNum_set3.setBounds(380, 340, 100, 40);

        cardNum_set4.setBackground(new Color(0,0,0,0));
        cardNum_set4.setFont(new java.awt.Font("OCR A Std", 0, 32)); // NOI18N
        cardNum_set4.setForeground(new java.awt.Color(247, 247, 247));
        cardNum_set4.setBorder(null);
        cardNum_set4.setOpaque(false);
        getContentPane().add(cardNum_set4);
        cardNum_set4.setBounds(500, 340, 100, 40);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/credit-card-icon.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 50, 670, 420);

        jPanel1.setBackground(new java.awt.Color(86, 86, 86));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 520));
        jPanel1.setLayout(null);

        btnTransaction.setText("Do the Transaction");
        btnTransaction.setBorder(null);
        btnTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransactionActionPerformed(evt);
            }
        });
        jPanel1.add(btnTransaction);
        btnTransaction.setBounds(528, 489, 123, 43);

        feedback.setBackground(new Color(0,0,0,0));
        feedback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        feedback.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(feedback);
        feedback.setBounds(76, 489, 379, 43);

        cashireID.setBackground(java.awt.Color.gray);
        cashireID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cashireID.setForeground(new java.awt.Color(255, 255, 255));
        cashireID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cashireID.setText("SID00001");
        cashireID.setToolTipText("POS ID");
        cashireID.setBorder(null);
        jPanel1.add(cashireID);
        cashireID.setBounds(540, 20, 110, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("POS ID :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(480, 20, 80, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 760, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cardNum_set2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNum_set2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNum_set2ActionPerformed

    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sampleSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sampleSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sampleSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sampleSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new sampleSimulator().setVisible(true);
            }
        });
        
    }
    
    
    
    
        private void SetIcon(){
        try {
            
            URL url = ClassLoader.getSystemResource("pic/cards.png");
            Toolkit kit = Toolkit.getDefaultToolkit();
            Image img = kit.createImage(url);
            setIconImage(img);
        
            
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
        
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

   
    
    
    
    private String amount = "100"; //for example
    private String sellerID;
            
    private String digitSet1, digitSet2, digitSet3, digitSet4;
    public String fullCardNumber;
    
    
    
    
    
    
    
    TheBank_DatabaseConnector obj_BankDB = new TheBank_DatabaseConnector();
       
    
    
    private void btnTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransactionActionPerformed
        
        digitSet1 = cardNum_set1.getText();
        digitSet2 = cardNum_set2.getText();
        digitSet3 = cardNum_set3.getText();
        digitSet4 = cardNum_set4.getText();
        
        fullCardNumber = digitSet1 + digitSet2 + digitSet3 + digitSet4;
        
        sellerID = cashireID.getText();
        
        //System.out.println(fullCardNumber);
        
        
       obj_BankDB.Transaction_Handler(fullCardNumber, amount, sellerID);
    }//GEN-LAST:event_btnTransactionActionPerformed

    
    
    
    public static void FeedBack(String msg){
        feedback.setText(msg);
    } 
    
   

    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransaction;
    private javax.swing.JTextField cardNum_set1;
    private javax.swing.JTextField cardNum_set2;
    private javax.swing.JTextField cardNum_set3;
    private javax.swing.JTextField cardNum_set4;
    private javax.swing.JTextField cashireID;
    private static javax.swing.JLabel feedback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    


}
